### ISSUE TITLE
[bug] 버튼 영역이 중복으로 잡혀 제대로 눌리지 않는 문제

### ISSUE THREAD

**Issue by xwoud** [weekFlex/Cartier#67]
## Task 내용
- [x] 한 뷰에 버튼이 여러개 있거나 TableView, Colloction View와 버튼이 같이 있을 때 한 버튼이 터치 영역을 넓게 차지하는 문제 발생

## 해당 task 관련 스크린샷
- 예시) 뒤로가기를 눌러도 체크 버튼을 누른것과 같이 동작
![화면 기록 2022-08-08 오후 2 47 55](https://user-images.githubusercontent.com/51286963/183348437-67386a4e-466c-498c-892f-4b3bc08be829.gif)

## things to consider, personal feedback
- 모든 뷰에서 동시다발적으로 일어나는 일
- 8/12(금)까지 찾아보기

**Comment by xwoud** [comment]
이유를 찾았습니다 ! 
혜린언니가 작성한 것 같은 extension인데 `MyPageHomeVC` 하단에 있습니다
```swift 
extension UIButton {

  open override func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
    let margin: CGFloat = 500
    let hitArea = self.bounds.insetBy(dx: -margin, dy: -margin)
    return hitArea.contains(point)
  }
}
```
이 extension이 모든 UIButton에 적용되면서 터치 영역이 x,y 500만큼 늘어난 것 같아요 :)
다행히 이 extension을 주석 처리하고 실행해봤을때는 문제가 해결되었습니다 !

언니가 이 함수를 override 해서 사용하고 싶다면 모든 UIButton을 대상으로 하지 않고, 
특정 Button Class를 생성해서 그 class만 point 함수를 override하게 생성하면 될 것 같아요 !
참고 링크 : https://ios-development.tistory.com/694

일단은 이 extension을 제거하고 develop에 merge를 하고, 우리 각 브런치에서 rebase를 한 뒤에 잘 되는 상황에서 작업을 이어나가는게 좋을 것 같습니다.
그리고 새로 브런치를 파서 이 extension을 원래 사용하던 얘를 언니가 수정하는게 좋을 것 같아요! 어떤가요 😁

**Comment by kacey0416** [comment]
헐 드뎌 찾아냈구나ㅜㅜ수고했습니다ㅠㅠㅠㅠㅠ짱이야... 요건 제가 작성한게 아니라서 무슨 용도로 있는 익스텐션인지 모르겠네요ㅠㅠ 사용되는 곳 보니까 마이페이지에서만 쓰이는 거  같은데 일단 제거하고 진행해도 될 것 같습니다~!
